package models;
// Generated Aug 23, 2019 9:15:04 PM by Hibernate Tools 4.3.1



/**
 * Formateurs generated by hbm2java
 */
public class Formateurs  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String prenom;
     private String email;
     private String telephone;

    public Formateurs() {
    }

    public Formateurs(String nom, String prenom, String email, String telephone) {
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.telephone = telephone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }




}


